### ISSUE TITLE
📌 Roadmap

### ISSUE THREAD

**Issue by h-a-n-a** [speedy-js/speedy-benchmark-action#1]
- [ ] Support GitHub Actions
      - [ ] With commands:
      - [ ]  GITHUB_TOKEN
- [ ] Core API 
    - [ ] Speedy performance plugin
- [ ] Fixtures
    - [ ] Arco Design Project integration
- [ ] Website
    - [ ] PR Status comparision with main branch, deployed on Vercel
    - [ ] Include DB for history analysis
